add error handling to status check
set a proper exit code if oidc agent is not reachable

this commit fixes a bug when oidc-agent --status is called and the oidc agent is not reachable (e.g. due to a not set environment variable). The old output looks like this

```text
Could not get the socket path from env var 'OIDC_SOCK'. Have you set the env var?
Could not decode json: (null)
This seems to be a bug. Please hand in a bug report.
Error: Argument is NULL in function getJSONValuesFromString
```

after this commit, the output looks like

```text
Could not get the socket path from env var 'OIDC_SOCK'. Have you set the env var?
Error: Env var not set
```

the exit code becomes 1 (EXIT_FAILURE) in those cases.